# Generated by Django 4.2.3 on 2024-06-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, null=True)),
                ('car', models.CharField(choices=[('Kia', 'Kia'), ('Suzuki Swift', 'Suzuki Swift'), ('Mahindra Scorpio', 'Mahindra Scorpio'), ('Hyundai', 'Hyundai')], max_length=100, null=True)),
                ('destination', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
