# Generated by Django 4.2.3 on 2024-06-22 09:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_bookings_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('car', models.CharField(choices=[('Kia', 'Kia'), ('Suzuki Swift', 'Suzuki Swift'), ('Mahindra Scorpio', 'Mahindra Scorpio'), ('Hyundai', 'Hyundai')], max_length=100, null=True)),
                ('destination', models.CharField(max_length=100, null=True)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
