# Generated by Django 4.2.3 on 2024-06-22 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_client_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='car',
        ),
        migrations.RemoveField(
            model_name='client',
            name='destination',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('others', 'others')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(choices=[('Kia', 'Kia'), ('Suzuki Swift', 'Suzuki Swift'), ('Mahindra Scorpio', 'Mahindra Scorpio'), ('Hyundai', 'Hyundai')], max_length=100, null=True)),
                ('pickup_location', models.CharField(max_length=255, null=True)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('pickup_date', models.DateTimeField()),
                ('dropoff_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
            ],
        ),
    ]
