# Generated by Django 4.2.3 on 2024-06-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_client_car_remove_client_destination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contact',
            new_name='client_contact',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='client_email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='gender',
            new_name='client_gender',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='client_name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
