# Generated by Django 4.2.3 on 2024-06-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_contact_client_client_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_name',
            new_name='name',
        ),
    ]
