# Generated by Django 4.2.3 on 2024-07-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_client_contact_client_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('Kia', 'Kia'), ('Suzuki Swift', 'Suzuki Swift'), ('Mahindra Scorpio', 'Mahindra Scorpio'), ('Hyundai', 'Hyundai')], max_length=20, null=True)),
                ('rental_rate', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
