# Generated by Django 4.2.3 on 2024-07-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_booking_car_alter_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car',
            field=models.CharField(choices=[('Kia', 'Kia'), ('Suzuki Swift', 'Suzuki Swift'), ('Mahindra Scorpio', 'Mahindra Scorpio'), ('Hyundai', 'Hyundai'), ('SUV', 'SUV'), ('Sedan', 'Sedan')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Kia', 'Kia'), ('Suzuki Swift', 'Suzuki Swift'), ('Mahindra Scorpio', 'Mahindra Scorpio'), ('Hyundai', 'Hyundai'), ('SUV', 'SUV'), ('Sedan', 'Sedan')], max_length=20, null=True),
        ),
    ]
