# Generated by Django 4.2.3 on 2024-07-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_booking_car_alter_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
