# Generated by Django 4.2.3 on 2024-07-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_booking_client_delete_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dropoff_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
