# Generated by Django 4.2.3 on 2024-07-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_booking_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Kia', 'Kia'), ('Suzuki Swift', 'Suzuki Swift'), ('Mahindra Scorpio', 'Mahindra Scorpio'), ('Hyundai', 'Hyundai'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Tata', 'Tata'), ('Volvo', 'Volvo'), ('Bajaj', 'Bajaj'), ('Honda', 'Honda')], max_length=20, null=True),
        ),
    ]
