# Generated by Django 4.2.3 on 2024-07-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_booking_car_alter_booking_dropoff_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
